export const dropdownItemsCountry = [
  { href: '/news/ae', text: 'ОАЭ' },
  { href: '/news/ar', text: 'Аргентина' },
  { href: '/news/at', text: 'Австрия' },
  { href: '/news/au', text: 'Австралия' },
  { href: '/news/be', text: 'Бельгия' },
  { href: '/news/bg', text: 'Болгария' },
  { href: '/news/br', text: 'Бразилия' },
  { href: '/news/ca', text: 'Канада' },
  { href: '/news/ch', text: 'Швейцария' },
  { href: '/news/cn', text: 'Китай' },
  { href: '/news/co', text: 'Колумбия' },
  { href: '/news/cu', text: 'Куба' },
  { href: '/news/cz', text: 'Чехия' },
  { href: '/news/de', text: 'Германия' },
  { href: '/news/eg', text: 'Египет' },
  { href: '/news/fr', text: 'Франция' },
  { href: '/news/gb', text: 'Великобритания' },
  { href: '/news/gr', text: 'Греция' },
  { href: '/news/hk', text: 'Гонконг' },
  { href: '/news/hu', text: 'Венгрия' },
  { href: '/news/id', text: 'Индонезия' },
  { href: '/news/ie', text: 'Ирландия' },
  { href: '/news/il', text: 'Израиль' },
  { href: '/news/in', text: 'Индия' },
  { href: '/news/it', text: 'Италия' },
  { href: '/news/jp', text: 'Япония' },
  { href: '/news/kr', text: 'Южная Корея' },
  { href: '/news/lt', text: 'Литва' },
  { href: '/news/lv', text: 'Латвия' },
  { href: '/news/ma', text: 'Марокко' },
  { href: '/news/mx', text: 'Мексика' },
  { href: '/news/my', text: 'Малайзия' },
  { href: '/news/ng', text: 'Нигерия' },
  { href: '/news/nl', text: 'Нидерланды' },
  { href: '/news/no', text: 'Норвегия' },
  { href: '/news/nz', text: 'Новая Зеландия' },
  { href: '/news/ph', text: 'Филиппины' },
  { href: '/news/pl', text: 'Польша' },
  { href: '/news/pt', text: 'Португалия' },
  { href: '/news/ro', text: 'Румыния' },
  { href: '/news/rs', text: 'Сербия' },
  { href: '/news/ru', text: 'Россия' },
  { href: '/news/sa', text: 'Саудовская Аравия' },
  { href: '/news/se', text: 'Швеция' },
  { href: '/news/sg', text: 'Сингапур' },
  { href: '/news/si', text: 'Словения' },
  { href: '/news/sk', text: 'Словакия' },
  { href: '/news/th', text: 'Таиланд' },
  { href: '/news/tr', text: 'Турция' },
  { href: '/news/tw', text: 'Тайвань' },
  { href: '/news/ua', text: 'Украина' },
  { href: '/news/us', text: 'США' },
  { href: '/news/ve', text: 'Венесуэла' },
  { href: '/news/za', text: 'ЮАР' },
];

export const dropdownItemsTime = [
  { href: '/news/today', text: 'За сегодня' },
  { href: '/news/past7days', text: 'Последние 7 дней' },
  { href: '/news/month', text: 'За текущий месяц' },
  { href: '/news/year', text: 'За текущий год' },
];

export const dropdownItemsCategory = [
  { href: '/news/business', text: 'Бизнес' },
  { href: '/news/entertainment', text: 'Развлечения' },
  { href: '/news/general', text: 'Общее' },
  { href: '/news/health', text: 'Здоровье' },
  { href: '/news/science', text: 'Наука' },
  { href: '/news/sports', text: 'Спорт' },
  { href: '/news/technology', text: 'Технологии' },
];
